[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "http://18.189.118.160:8000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws/*"
  to = "ws://18.189.118.160:8000/:splat"
  status = 200
  force = true
